### ISSUE TITLE
issue with associating a PLP program with a directory

### ISSUE THREAD

**Issue by ssohoni** [Progressive-Learning-Platform/PLPAssembler#36]
Currently we are associating a program with just the name of the directory. As a result, on loading that program, all .plp files in that directory are loaded. However, someone could be saving some .plp files as backups, or may not intend for some .plp files in that directory to be associated with that "project". Would it be better to allow for the concept of a PLP Project? Could we allows the user to manually exclude certain files from the project. This will also enable someone to organize their PLP project across multiple directories.

**Comment by harsha-kadekar** [comment]
This has been fixed with the new implementation of the PLP Program. Now Plp Program is not associated to a directory but rather it is an compressed file with .plp extension. Inside that file, it has a meta data file containing the list of .asm files associated to that program and the order in which these files need to be loaded by the PlpProgram.
